# Resolve react_native_pods.rb with node to allow for hoisting
ENV['RCT_USE_RN_DEP'] = '0'
ENV['RCT_USE_PREBUILT_RNCORE'] = '0'
ENV['RCT_BUILD_HERMES_FROM_SOURCE'] = 'true'
ENV['SOFTBOOK_REACT_NATIVE_PATH'] = File.expand_path('../node_modules/react-native', __dir__)

hermes_podspec = File.join(ENV['SOFTBOOK_REACT_NATIVE_PATH'], 'sdks/hermes-engine/hermes-engine.podspec')
unless File.read(hermes_podspec).include?('${SOFTBOOK_REACT_NATIVE_PATH}')
  raise 'Hermes podspec is not normalized. Run npm ci without --ignore-scripts before installing Pods.'
end

require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'SoftbookCET' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
  end
end
