// Generated by scripts/install_bundled_card_library.mjs.
import cet4_0 from '../../../../infra/cloudbase/functions/softbook-api/card-content/cet4-0.json';
import cet4_1 from '../../../../infra/cloudbase/functions/softbook-api/card-content/cet4-1.json';
import cet4_2 from '../../../../infra/cloudbase/functions/softbook-api/card-content/cet4-2.json';
import cet4_3 from '../../../../infra/cloudbase/functions/softbook-api/card-content/cet4-3.json';
import cet4_4 from '../../../../infra/cloudbase/functions/softbook-api/card-content/cet4-4.json';
import cet4_5 from '../../../../infra/cloudbase/functions/softbook-api/card-content/cet4-5.json';
import cet4Assets from '../../../../infra/cloudbase/functions/softbook-api/card-content/cet4-assets.json';
import cet6_0 from '../../../../infra/cloudbase/functions/softbook-api/card-content/cet6-0.json';
import cet6_1 from '../../../../infra/cloudbase/functions/softbook-api/card-content/cet6-1.json';
import cet6_2 from '../../../../infra/cloudbase/functions/softbook-api/card-content/cet6-2.json';
import cet6_3 from '../../../../infra/cloudbase/functions/softbook-api/card-content/cet6-3.json';
import cet6_4 from '../../../../infra/cloudbase/functions/softbook-api/card-content/cet6-4.json';
import cet6_5 from '../../../../infra/cloudbase/functions/softbook-api/card-content/cet6-5.json';
import cet6_6 from '../../../../infra/cloudbase/functions/softbook-api/card-content/cet6-6.json';
import cet6Assets from '../../../../infra/cloudbase/functions/softbook-api/card-content/cet6-assets.json';
import type {LearningCardRecord} from './sourceContract';
import type {LearningTrack} from './model';
import type {BundledAudioAsset} from './bundledCardLibrary';
export const bundledCardData: Record<LearningTrack, {cards: LearningCardRecord[]; assets: BundledAudioAsset[]}> = {
cet4: {cards: [...cet4_0, ...cet4_1, ...cet4_2, ...cet4_3, ...cet4_4, ...cet4_5] as LearningCardRecord[], assets: cet4Assets as BundledAudioAsset[]},
cet6: {cards: [...cet6_0, ...cet6_1, ...cet6_2, ...cet6_3, ...cet6_4, ...cet6_5, ...cet6_6] as LearningCardRecord[], assets: cet6Assets as BundledAudioAsset[]}
};
